title = "Max Anderson"

[params.author]
name = "Max Anderson"
image = "img/Max.png"
headline = """
<p class="mb-3">
I'm a Sr. Systems Engineer specializing in DevOps and Cloud Infrastructure
</p>
"""
bio = "I'm from sunny Southwest Florida, but currently live in the Atlanta Metro Area working for Georgia United Credit Union. In my free time I enjoy watching Formula 1 ğŸï¸, being a dog dad ğŸ•, and homelabbing ğŸ‘¨ğŸ»â€ğŸ”¬."
links = [
  { github = "https://github.com/MaxAnderson95" },
  { linkedin = "https://www.linkedin.com/in/maxanderson95" },
  { email = "mailto:max.a.anderson95@gmail.com" },
]
